### ISSUE TITLE
Linking project markdown descriptions with external source like GitHub README

### ISSUE THREAD

**Issue by TheCSDev** [modrinth/labrinth#503] opened 2022-12-19 14:15 UTC
### Is your feature request related to a problem? Please describe.

I will outline the issues and present my suggested solution in the following section.

### Describe the solution you'd like

I would like to propose a feature that would enable users to link their Modrinth project descriptions to their GitHub repository README.md file, allowing any updates to the README to be automatically reflected in the project description. This would improve the user experience and ensure that project descriptions are always up-to-date.

Without this feature, users must manually update their project description any time they make a change to their README. This is time consuming and increases the likelihood of errors, as well as making it difficult to keep project descriptions up-to-date. By creating a link between the two, this hassle is eliminated and users can rest assured that their project descriptions will always reflect the most up-to-date information.

Sidenote:  
It's already time consuming enough having to worry about WYSIWYG on CurseForge as well, but that's irrelevant.

### Describe alternatives you've considered

1. <kbd>CTRL</kbd> + <kbd>C</kbd>
2. <kbd>CTRL / ALT</kbd> + <kbd>TAB</kbd>
3. <kbd>CTRL</kbd> + <kbd>V</kbd>

^ Turns out those steps are useful for more than just writing code.

### Some extra info on how I think this could work
This feature can easily be achieved utilizing the GitHub API. A simple GET request, such as the following, can be used to obtain the desired GitHub repository README.md file: 

`GET` `https://api.github.com/repos/{owner}/{repo}/readme`

Example:  
`GET` `https://api.github.com/repos/Modrinth/labrinth/readme`

The response will be a JSON Object containing the `content` field that represents has the contents of README. Once the README has been obtained, it can then be put in place of a given project's description, allowing any changes to the README to be automatically reflected in the project description.

Keep in mind that the `content` field in the returned JSON response is likely `base64` encoded. Use the `encoding` field to check what encoding was used to encode the `content`.

**Comment by osfanbuff63** [comment] 2022-12-19 14:51
This is already implemented in Minotaur (the Gradle plugin), but this good be a nice feature.

The only problem with how it could work is what if it's hosted on Gitlab (likely irrelevant because it uses its own Markdown spec) or some instance of Gitea/Forgejo (e.g https://codeberg.org)?

**Comment by TheCSDev** [comment] 2022-12-19 15:38
Yeah, my feature request fails to address instances of repositories hosted outside of GitHub. I'm not sure what the solution would be in those cases, but perhaps those other services have their own APIs that could be used for integration? Even then, working with multiple APIs could be a hassle. A possible solution could be to start off with GitHub APIs, and then after that, if there is sufficient demand, roll out support for other platforms.

**Comment by osfanbuff63** [comment] 2022-12-19 16:48
In Gitea (which iirc uses a GFM-like spec), you can [get the contents of a file](https://try.gitea.io/api/swagger#/repository/repoGetContents) so that could be used potentially. However, how would you detect what kind of repo it is besides say `github.com` or `codeberg.org`?

**Comment by Andre601** [comment] 2022-12-19 16:52
I recall opening a similar request to allow importing data from a GitHub repo (README content, sponsor/donation links, issue tracker, wiki (if present), etc.) into the project. It would cut out repetitive work you had to do.

**Comment by Geometrically** [comment] 2022-12-19 16:53
Github has this API: https://docs.github.com/en/rest/repos/contents?apiVersion=2022-11-28

The main issue is subscribing to webhooks/building an integration directly to sync it. We could do it for Github and possibly GitLab, but for newer Git sites they often don't support the APIs neeeded

**Comment by TheCSDev** [comment] 2022-12-19 17:11
> I recall opening a similar request to allow importing data from a GitHub repo (README content, sponsor/donation links, issue tracker, wiki (if present), etc.) into the project. It would cut out repetitive work you had to do.

I like that idea as well, and it also likely wouldn't require subscribing to webhooks as mentioned in the reply above, as you could use the APIs to grab the data at the time of importing it. As for linking a README to a project's description, then yeah, that would be a lot more complicated I guess.

**Comment by funnyboy-roks** [comment] 2023-04-23 05:45
Since this isn't yet a feature, I've created a GitHub action for anyone who desires this functionality: [`modrinth-auto-description`](https://github.com/marketplace/actions/modrinth-auto-description)

**Comment by triphora** [comment] 2023-05-14 17:50
Duplicate of modrinth/.github#5

**Closed by triphora** 2023-05-14 17:50 UTC
Labels: feature request
