### ISSUE TITLE
Wrong url on mod update notification

### ISSUE THREAD

**Issue by SrGnis** [modrinth/labrinth#286] opened 2022-02-04 07:33 UTC
I recived a mod update notification with the url:
https://modrinth.com/kCMvEtYh/version/yVaj4Iim
This leads to a **Page not found**
The correct url should be:
https://modrinth.com/mod/earthbounds/version/yVaj4Iim

**Comment by wafflecoffee** [comment] 2022-02-21 17:22
This is a duplicate of modrinth/knossos#349
(sorry, I know this issue came first, but this is ultimately a frontend issue)

**Closed by wafflecoffee** 2022-02-21 17:22 UTC
Labels: bug
